### ISSUE TITLE
ReferenceError: Can't find variable: bds

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#176]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/140/](https://rollbar.com/instantlogosearch/instantlogosearch/items/140/)

```

ReferenceError: Can't find variable: bds
  File "http://instantlogosearch.com/", line 1, in [anonymous]
```

**Comment by CuveeCui** [comment]
can not open the address
