### ISSUE TITLE
ReferenceError: Can't find variable: hilitor

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#188]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/151/](https://rollbar.com/instantlogosearch/instantlogosearch/items/151/)

```

ReferenceError: Can't find variable: hilitor
  File "http://instantlogosearch.com/", line 1, in [anonymous]
```

**Comment by rjdhania** [comment]
Please clarify how you managed to resolve this. I am stuck on this and it looks like some plugin is causing this issue. I am not able to identify the plug in. Any help/suggestions will be appreciated.

Thanks,
Rajesh

**Comment by jfeust** [comment]
@saiichihashimoto and @rjdhania Did either of you figure this out? I'm also seeing in in rollbar for our app,  and can't track it down.
