### ISSUE TITLE
Uncaught TypeError: Cannot read property 'controls' of undefined

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#196]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/159/](https://rollbar.com/instantlogosearch/instantlogosearch/items/159/)

```

TypeError: Cannot read property 'controls' of undefined
  File "source)", line unknown, in Array.onKeyUp (unknown
  File "source", line unknown, in unhook (unknown
  File "source", line unknown, in HTMLDocument.unhook_f (unknown
```

**Comment by AnkushCr07** [comment]
Hi @saiichihashimoto 
Please let me know if you were able to solve this issue.
Thanks!!
