### ISSUE TITLE
Uncaught ReferenceError: diableNightMode is not defined

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#197]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/160/](https://rollbar.com/instantlogosearch/instantlogosearch/items/160/)

```

ReferenceError: diableNightMode is not defined
  File "<anonymous>", line 1, in [anonymous]
```

**Comment by fonziemedia** [comment]
Hi, I'm getting the same error on my app, did you find out what was causing it? I suspect this might be a plugin/add-on... Any help would be appreciated, thanks.

**Comment by saiichihashimoto** [comment]
No, sorry. Just closed it.

**Comment by vaibhavi3t** [comment]
@saiichihashimoto 
Hi,  Same error is reported in Sentry. Not able to find out why it's happening.
Any insight?

**Comment by korochinsky** [comment]
@vaibhavi3t 
Hey, we also see this in Sentry. All of the errors of this kind are coming from one particular user, so I'm pretty sure it comes from some Chrome extension.
