### ISSUE TITLE
TypeError: null is not an object (evaluating 'elt.parentNode')

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#222]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/185/](https://rollbar.com/instantlogosearch/instantlogosearch/items/185/)

```

TypeError: null is not an object (evaluating 'elt.parentNode')
  File "http://instantlogosearch.com/", line 1, in [anonymous]
  File "http://instantlogosearch.com/", line 1, in global code
```

**Comment by dugwood** [comment]
Sorry to bother you, but did you manage to find what was causing this? I'm having the same issue on my website, but I can't figure out what is causing all this. Thanks.

**Comment by saiichihashimoto** [comment]
I didn't, but rollbar was spamming me so I stopped it and closed it's issues.

**Comment by dugwood** [comment]
OK, thanks.
